Code mirror
bjones1/CodeChat_Editor pull request #14
Opened 2023-04-20 00:52 UTC by BrandonBlack-13

Iterated through main and commented on CodeMirror 'Webserver.rs' on how the save function works.

2023-04-21 19:36 UTC, bjones1 requested changes

2023-04-21 19:36 UTC, bjones1 commented on server/Cargo.lock
Don't commit this file -- it should only be committed before a release.

2023-04-21 19:36 UTC, bjones1 commented on server/Cargo.lock
Either edit your commit history, or just revert changes to this.

2023-04-22 01:31 UTC, BrandonBlack-13 commented
I added a commit where I just removed the Cargo Lock file. Let me know if this fixed it or if I need to change anything else!

2023-04-24 14:13 UTC, bjones1 requested changes

2023-04-24 14:13 UTC, bjones1 commented on client/package-lock.json
Same as cargo.lock -- don't commit this.

2023-04-24 19:45 UTC, closed without merging