new c.pest file
bjones1/CodeChat_Editor pull request #40
Opened 2024-11-10 19:39 UTC by williamaguessy

I tried to ad the possibility of having "multiligne string" on c.pest. It works but after the first string detection in the pest editor, the parser is not able to recognise the comment anymore.

2024-11-11 18:38 UTC, bjones1 commented
- [ ] Remove commits of `Cargo.lock` or `package.lock`.
- [ ] Send this PR to the `pest` branch, instead of the `main` branch.

2024-11-13 20:10 UTC, williamaguessy commented
I put my change into the python pest file, for now it can well see inline comment in multiligne string as code block in this case ''' # this in not a comment ''', but not is this case : print(''' # this is not a comment '''). I aslo tried to revert my previous wrong commits.

2024-11-14 17:14 UTC, bjones1 requested changes

2024-11-14 17:14 UTC, bjones1 commented on server/src/lexer/pest_parser.rs
>      use crate::lexer::{CodeDocBlock, DocBlock};
Revert these changes.

2024-11-14 17:14 UTC, bjones1 commented on server/src/lexer/pest/python.pest
> +code_block = { multiline_string | code_line+ }
Not the right approach -- a code block is:
- Not a doc block, followed by non-newline characters then a newline OR
- Not a doc block, followed by non-newline characters  then EOI OR
- non-newline characters followed by a newline OR
- a multi-line string

2024-11-14 17:15 UTC, bjones1 commented
> I put my change into the python pest file, for now it can well see inline comment in multiligne string as code block in this case ''' # this in not a comment ''', but not is this case : print(''' # this is not a comment '''). I aslo tried to revert my previous wrong commits.

Progress -- see my review comments.

2024-11-18 16:29 UTC, bjones1 commented
I see progress, but nothing from what we discussed in my office. I want a fully-working PR ready before we meet tomorrow.

2024-11-19 18:42 UTC, williamaguessy commented
Here is the change we discussed during our meeting but it's not working for the moment. It only recognise multiligne string but not normal code block anymore

2024-11-19 18:52 UTC, williamaguessy commented
in fact it detect only the multiline string evne if it is one of the two other case. The definition isn't complete

2024-12-03 01:51 UTC, williamaguessy commented
I have made the changes to handle single and double quotes with backslashes, and I have also added support for parsing both ''' and """ multiline strings. Initially, there was a conflict between the two rules because the parser interpreted the first two double quotes as the start of a multiline backslash. To resolve this, I replaced a * with a +. multiline_string_backslash = { 
"\"" ~ (("\\" ~ ANY) | (!( "\"" | NEWLINE ) ~ ANY))**+** ~ "\"" 
}

2024-12-18 00:23 UTC, closed without merging